name: Release Corne Classic

on:
  push:
    tags:
      - 'corne-classic-v[0-9]+.[0-9]+*'

jobs:
  release-gerber-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Export corne-classic gerber
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: .kiplot.yml
        dir: corne-classic/gerber
        board: corne-classic/pcb/corne-classic.kicad_pcb
        schema: corne-classic/pcb/corne-classic.sch
    - name: Export top plate gerber
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: .kiplot.yml
        dir: plates/pcb/top/gerber
        board: plates/pcb/top/corne-top-plate.kicad_pcb
        schema: plates/pcb/top/corne-top-plate.sch
    - name: Export bottom plate gerber
      uses: nerdyscout/kicad-exports@v2.0
      with:
        config: .kiplot.yml
        dir: plates/pcb/bottom/gerber
        board: plates/pcb/bottom/corne-bottom-plate.kicad_pcb
        schema: plates/pcb/bottom/corne-bottom-plate.sch

    - name: Zip Gerber files
      run: |
          zip -r --junk-paths corne-classic-gerber.zip corne-classic/gerber
          zip -r --junk-paths plates-top-gerber.zip plates/pcb/top/gerber
          zip -r --junk-paths plates-bottom-gerber.zip plates/pcb/bottom/gerber
          zip -r --junk-paths plates.zip plates/common

    - name: Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: "*.zip"
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
