name: Release Corne Light

on:
  push:
    tags:
      - 'corne-light-v[0-9]+.[0-9]+*'

jobs:
  release-gerber-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Export corne-light gerber
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: .kiplot.yml
        dir: corne-light/gerber
        board: corne-light/pcb/corne-light.kicad_pcb
        schema: corne-light/pcb/corne-light.kicad_sch
    - name: Export top plate gerber
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: .kiplot.yml
        dir: plates/pcb/top/gerber
        board: plates/pcb/top/corne-top-plate.kicad_pcb
    - name: Export bottom plate gerber
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: .kiplot.yml
        dir: plates/pcb/bottom/gerber
        board: plates/pcb/bottom/corne-bottom-plate.kicad_pcb
    - name: Export top plate mini gerber
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: .kiplot.yml
        dir: plates/pcb/top-mini/gerber
        board: plates/pcb/top-mini/corne-top-plate.kicad_pcb
    - name: Export bottom plate mini gerber
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: .kiplot.yml
        dir: plates/pcb/bottom-mini/gerber
        board: plates/pcb/bottom-mini/corne-bottom-plate.kicad_pcb
    - name: Export top-alps plate gerber
      uses: INTI-CMNB/KiBot@v2_k6
      with:
        config: .kiplot.yml
        dir: plates/pcb/top-alps/gerber
        board: plates/pcb/top-alps/corne-top-alps-plate.kicad_pcb

    - name: Zip Gerber files
      run: |
          zip -r --junk-paths corne-light-gerber.zip corne-light/gerber
          zip -r --junk-paths plates-top-gerber.zip plates/pcb/top/gerber
          zip -r --junk-paths plates-top-mini-gerber.zip plates/pcb/top-mini/gerber
          zip -r --junk-paths plates-top-alps-gerber.zip plates/pcb/top-alps/gerber
          zip -r --junk-paths plates-bottom-gerber.zip plates/pcb/bottom/gerber
          zip -r --junk-paths plates-bottom-mini-gerber.zip plates/pcb/bottom-mini/gerber
          zip -r --junk-paths plates.zip plates/common
          zip -r --junk-paths plates-alps.zip plates/alps
          zip -r --junk-paths plates-mini.zip plates/mini

    - name: Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: "*.zip"
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
